trigger:
  tags:
    include:
    - '*'

stages:
- stage: DEV
  displayName: Generate packages for DEV environment
  pool:
    vmImage: ubuntu-latest

  variables:
  - group: DEV
  - name: VERSION-ID
    value: $[replace(variables['BUILD.SOURCEBRANCHNAME'], 'v', '')]
  - name: DEPENDENCY-PACK-NAME
    value: "dependency-pack_$(VERSION-ID).deb"
  - name: DEPENDENCY-PACK-PINNING-NAME
    value: "dependency-pack-pinning_$(VERSION-ID).deb"

  jobs:
  - job: PackageGeneration
    steps:
    - script: src/build-package.sh 'package-history' 'output' "$(VERSION-ID)"
      displayName: 'Generate packages locally'

    - script: |
        curl -u "$USERNAME:$PASSWORD" -XPUT "$(ARTIFACTORY-URL)/$(DEPENDENCY-PACK-NAME);deb.distribution=focal;deb.component=main;deb.architecture=amd64;deb.architecture=64bit-arm" -T "output/$(DEPENDENCY-PACK-NAME)" &&
        curl -u "$USERNAME:$PASSWORD" -XPUT "$(ARTIFACTORY-URL)/$(DEPENDENCY-PACK-PINNING-NAME);deb.distribution=focal;deb.component=main;deb.architecture=amd64;deb.architecture=64bit-arm" -T "output/$(DEPENDENCY-PACK-PINNING-NAME)"
      displayName: 'Upload packages to Artifactory'
      env: # this is required for secret library variables
          USERNAME: $(ARTIFACTORY-USERNAME)
          PASSWORD: $(ARTIFACTORY-PASSWORD)