# This workflow generates new DEB package whenever relevant changes are detected

name: Generate DEB Package

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get the tag version
        id: get_tag_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF#refs/tags/} | tr -d 'v')

      - name: Generate DEB package
        run: src/build-package.sh 'package-history' 'output' ${{ steps.get_tag_version.outputs.VERSION }}

      - name: Release and publish dependency package
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/dependency-pack/DEBIAN/control
            output/dependency-pack.deb
            output/dependency-pack-pinning/DEBIAN/control
            output/dependency-pack-pinning.deb