# This workflow generates new DEB package whenever relevant changes are detected

name: Generate DEB Package

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate DEB package
        run: src/build-package.sh 'package-history' 'output'

      - name: Publish DEB package
        run: cat output/dependency-pack/DEBIAN/control
